### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by astarcev** [CleanTalk/csharp-antispam#1]
Пожалуйста, сделайте nuget пакет, очень неудобно каждый раз собирать самому и класть в рабочий репозиторий.
У нас все зависимости через nuget подтягиваются

**Comment by CleanTalk** [comment]
Хорошо, постараемся сделать. Отпишем сюда по готовности.

**Comment by CleanTalk** [comment]
Готово, версии обновляем и на nuget.org.
